name: mindm8
description: MindM8 MVP
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.10.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.2
  intl: ^0.20.2
  flutter_feather_icons: ^2.0.0
  flutter_svg: ^2.0.10
  firebase_core: "2.18.0"  # Use quotes to enforce exact version
  firebase_auth: "4.11.0"  # Use quotes to enforce exact version
  flutter_riverpod: "2.4.9" # Use quotes to enforce exact version
  dio: ^5.3.3
  flutter_dotenv: ^5.1.0
  flutter_local_notifications: 15.1.1
  timezone: ^0.9.1
  firebase_messaging: ^14.7.0
  flutter_launcher_icons: ^0.13.1
  http: ^1.0.0  # or latest
  googleapis_auth: ^1.4.0
  flutter_hooks: ^0.20.0
  url_launcher: ^6.1.0
  clipboard: ^0.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0



flutter:
  uses-material-design: true
  assets:
    - assets/logo_white.svg
    - assets/logo_black.svg
    - assets/google.png
    - assets/icon.png
    - .env

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  remove_alpha_ios: true